//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package instance

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceInitializationSpec) DeepCopyInto(out *InstanceInitializationSpec) {
	*out = *in
	if in.CloudInit != nil {
		in, out := &in.CloudInit, &out.CloudInit
		*out = new(CloudInitSpec)
		**out = **in
	}
	if in.Ignition != nil {
		in, out := &in.Ignition, &out.Ignition
		*out = new(IgnitionSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceInitializationSpec.
func (in *InstanceInitializationSpec) DeepCopy() *InstanceInitializationSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceInitializationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceInitializationSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
