on:
  push:
    branches:
      - "main"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: build image
        shell: bash
        env:
          QUAY_TOKEN: ${{secrets.QUAY_TOKEN}}
          REGISTRY: "quay.io/cluster-api-provider-kubemark"
          TAG: "latest"
        run: |
          echo $QUAY_TOKEN | docker login -u="cluster-api-provider-kubemark+capk_robot" quay.io --password-stdin
          make docker-build
          make docker-push
