on: [push, pull_request]
name: build
jobs:
  unit_test:
    if: (github.repository == 'kubernetes-sigs/cluster-api-provider-kubemark')
    strategy:
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # tag=v7.0.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
    - name: Test
      run: make test
    - name: Build
      run: make manager

  pr-verify:
    strategy:
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # tag=v7.0.0
      with:
        go-version: ${{ matrix.go-version }} 
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
    - name: verify
      run: make verify
