on: [push, pull_request]
name: build
jobs:
  unit_test:
    if: (github.repository == 'kubernetes-sigs/cluster-api-provider-kubemark')
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Test
      run: make test
    - name: Build
      run: make manager

  pr-verify:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }} 
    - uses: actions/checkout@v5
    - name: verify
      run: make verify
